apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPPrivilegedContainer
metadata:
  name: avesha-policy-pss-baseline-v2022-privileged-containers
spec:
  enforcementAction: deny
  match:
    excludedNamespaces:
      - kube-system
      - egs-monitoring
      - egs-gpu-operator
      - kt-postgresql
    kinds:
      - apiGroups:
          - ''
        kinds:
          - Pod
